### ISSUE TITLE
how to use multiple structs

### ISSUE THREAD

**Issue by HiroiImanishi** [membraneframework/unifex#29]
Excuse me, I have one more question.

In the Unifex library, at `c_src/example/example.h` a structure `MyState` is  defined.
When I'd like to define two or more structures, what should I write in this file?
Should I increase `enif_resource_open_type()` in `deps/unifex/lib/native_code_generator.ex`?
for example,
```
// c_src/example/example.h
#pragma once
typedef struct MyState UnifexNifState;
struct MyState {
  int a;
};
typedef UnifexNifState State;

//add this structure
struct MyState2 {
  int b;
};
#include "_generated/rclex.h"
```
Thanks.

**Comment by mat-hek** [comment]
Hi @HiroiImanishi , support for multiple resources is planned in the future, but currently Unifex handles only one resource per NIF (the `state`).  For now, a solution that comes to my mind is to create a single state that contains either `MyState` or `MyState2`, along with an enum specifying what kind of state is contained.

```c
typedef struct ContainerState UnifexNifState;
struct ContainerState {
  enum {MyStateType, MyState2Type} state_type;
  union {
    MyState my_state;
    MyState2 my_state2;
  };
};
```

**Comment by HiroiImanishi** [comment]
Thank you so much for comments, @mat-hek,
I see that support for multiple resources is future work. I will have to use so many resources, maybe so it is better to redesign my project than to adopt your idea....
Sincerely.

**Comment by HiroiImanishi** [comment]
Excuse me, @mat-hek 
I am studying Elixir and NIFs, so again I'd like to confirm it is currently impossible that multiple resources are created in one mix project (not one Module).
Can't nested modules do that?

**Comment by mat-hek** [comment]
As far as I understand, that's not true. See the 'resource objects' section of [erl_nif documentation](http://erlang.org/doc/man/erl_nif.html). Unifex supports only one resource type per NIF - that's the only limitation in this area. No idea how nested modules could be related to the problem.

**Comment by HiroiImanishi** [comment]
Hi, @mat-hek 
Thanks for comment, I understand that there may be multiple resources in one project.
 I have to study more about resource objects.

Thank you so much for answering my questions in these days...
Sincerely
