### ISSUE TITLE
Support for complex data types

### ISSUE THREAD

**Issue by ConnorRigby** [membraneframework/unifex#32]
the `enif` api supports creating lists and maps, but unifex does not seem to allow these complex types as params or return values

**Comment by mat-hek** [comment]
Hi @ConnorRigby, lists are supported as both parameters and return values:

```
spec fun([int]) :: [int]
```

However, they need some improvements:
- documentation :P
- support for nesting

Maps are not yet supported, but after fixing lists' issues adding them should be quite analogous.
