### ISSUE TITLE
Support returning literals in specs

### ISSUE THREAD

**Issue by mkaput** [membraneframework/unifex#39]
sometimes it could be handy to hide generation of constant literals inside unifex specs, for example to express `void` procedures, or known error atoms:

```elixir
spec remove_stream(state, stream_id :: unsigned) :: nil
spec create() :: {:ok :: label, state} | {:error :: label, :failed}
```

on ambiguous cases, unifex should raise a compilation error, e.g.:

```elixir
spec foo() :: {:error :: label, 8} | {:error :: label, 9}
```

**Comment by mkaput** [comment]
Currently as a workaround one may use `:: label`, though note it influences result creators' naming:

```
spec remove_stream(state, stream_id :: unsigned) :: (nil :: label)
spec create() :: {:ok :: label, state} | {:error :: label, :failed :: label}
```

**Comment by mickel8** [comment]
Moved to #61
