### ISSUE TITLE
Support C enums

### ISSUE THREAD

**Issue by mat-hek** [membraneframework/unifex#61]
From the elixir side, passing/returning enums could work the same way as passing atoms, but those atoms could be converted to C enums. The spec could look like:

```elixir
spec my_fun(some_argument :: :something | :something_else, :foo | :bar) :: :some_result | :another_result
sends {:some_message, status :: :status_x | :status_y}
```

that would generate
```C
enum MyFunSomeArgumentEnum{SOMETHING, SOMETHING_ELSE};
enum MyFunArgument2Enum{FOO, BAR};
enum MyFunResultEnum{SOME_RESULT, ANOTHER_RESULT};
enum SendSomeMessageStatusEnum{STATUS_X | STATUS_Y};
```

We could also allow specifying enums explicitly for multiple uses

```elixir
enum my_enum :: :option_one | :option_two | :option_three

spec my_fun(my_enum) :: my_enum
sends {:some_message, my_enum}
```

and the C side

```C
enum MyEnum{OPTION_ONE, OPTION_TWO, OPTION_THREE};
```

cc @mickel8 @mkaput @bblaszkow06

**Comment by mkaput** [comment]
aren't we using `UpperCase` for type names?

**Comment by mat-hek** [comment]
Didn't realize the standard :P updated the original post

**Comment by bblaszkow06** [comment]
Lol, you actually broke it even further, Marek meant **type** names.
```c
enum MyEnum{OPTION_ONE, OPTION_TWO, OPTION_THREE};
```
This convention is used by both [FFmpeg](https://ffmpeg.org/doxygen/4.1/group__lavu__sampfmts.html#gaf9a51ca15301871723577c730b5865c5) and [GStreamer] (https://gstreamer.freedesktop.org/documentation/videotestsrc/index.html#named-constants)

**Comment by FelonEkonom** [comment]
Maybe generate enums on native side in one place, e.g. spec looking like 
`spec my_fun(some_argument :: :something | :something_else, :foo | :bar) :: :some_result | :another_result
sends {:some_message, status :: :status_x | :status_y}`
would generate something like
`enum UnifexEnum{SOMETHING, SOMETHING_ELSE, FOO, BAR, SOME_RESULT, ANOTHER_RESULT, STATUS_X, STATUS_Y};`

I think, that giving all of these enums this same type would help in case, when, for example, this same enum occurs as a parameter in two different functions
