### ISSUE TITLE
Segfault when upgrading from 0.7.0 to 0.7.1

### ISSUE THREAD

**Issue by sax** [membraneframework/unifex#86]
The segfault occurs when using `membrane_rtc_engine` with a `Membrane.RTC.Engine..Endpoint.WebRTC` endpoint, when the first track is received.

Because it's a segfault, unfortunately I'm not able to get a whole lot of information. I did force recompile all deps, so it should have recompiled all the NIFs.

**Comment by bblaszkow06** [comment]
Fixed in #87
